name: shici
description: 中华诗词 - A Chinese classical poetry app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/poems.json

  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.otf
        - asset: assets/fonts/NotoSerifSC-Bold.otf
          weight: 700
